Numpy- Numerical python

Advantage of numpy Array
1. Allow several Mathematical Operations
2. Faster Operations

In [ ]:
import numpy as np

List Vs Numpy - Time Taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0011321899999998664


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5  # np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)

0.00015831900000051746


Numpy Arrays

In [ ]:
#list

list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating one dimension array

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype =float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays



In [ ]:
# create a numpy array of zeros

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones

y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# create an array of particular value

z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an identity matrix

a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values

b = np.random.random((3,4))
print(b)

[[0.49696863 0.63536035 0.29788948 0.72802704]
 [0.45207345 0.00662412 0.91055091 0.95078217]
 [0.66817425 0.90011014 0.99657538 0.0989094 ]]


In [40]:
# random integer value array within a specific range

c = np.random.randint(10, 100,(3, 5))
print(c)

[[74 34 42 59 90]
 [42 44 25 81 34]
 [91 38 97 21 74]]


In [31]:
# array of evenly spaced value --> specifying the number of value required

d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [32]:
# array of evenly spaced value --> specifying the step

e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [33]:
# convert a list to a numpy array

list2 = [10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [42]:
c = np.random.randint(10,90,(5,5))
print(c)

[[51 32 43 89 67]
 [32 13 53 59 88]
 [36 86 40 39 80]
 [84 67 24 78 89]
 [55 32 59 79 11]]


In [43]:
# array dimention

print(c.shape)

(5, 5)


In [44]:
# number of dimention

print(c.ndim)

2


In [45]:
# number of element in an array

print(c.size)

25


In [46]:
# checking the datatype of the value in the array

print(c.dtype)

int64


Mathamatical operation on a numpy array

In [47]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)  # conatenate or join two array


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [48]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[3 2 7]
 [9 5 6]
 [3 2 5]]
[[13 15 16]
 [14 10 15]
 [13 16 15]]


In [50]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[16 17 23]
 [23 15 21]
 [16 18 20]]
[[-10 -13  -9]
 [ -5  -5  -9]
 [-10 -14 -10]]
[[ 39  30 112]
 [126  50  90]
 [ 39  32  75]]
[[0.23076923 0.13333333 0.4375    ]
 [0.64285714 0.5        0.4       ]
 [0.23076923 0.125      0.33333333]]


In [52]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[16 17 23]
 [23 15 21]
 [16 18 20]]
[[-10 -13  -9]
 [ -5  -5  -9]
 [-10 -14 -10]]
[[ 39  30 112]
 [126  50  90]
 [ 39  32  75]]
[[0.23076923 0.13333333 0.4375    ]
 [0.64285714 0.5        0.4       ]
 [0.23076923 0.125      0.33333333]]


Array manipulation

In [53]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 5 8]
 [0 3 6]]
(2, 3)


In [54]:
# tranpose

trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 0]
 [5 3]
 [8 6]]
(3, 2)


In [55]:
trans2 = array.T
print(trans2)
print(trans2.shape)


[[9 0]
 [5 3]
 [8 6]]
(3, 2)


In [56]:
# reshaping a array

a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 5 5]
 [5 9 8]]
(2, 3)


In [59]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[2 5]
 [5 5]
 [9 8]]
(3, 2)
